name: tfshallow
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.7
  - h5py
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pillow
  - scipy
  - scikit-learn
  - yaml
  - tensorflow=1.15
